project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual